apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalCert.secretName }}
spec:
  refreshInterval: 1h             
  secretStoreRef:
    kind: SecretStore
    name: gcp-store               
  target:
    name: {{ .Values.externalCert.secretName }} 
    creationPolicy: Owner
  data:
  - secretKey: tls.crt
    remoteRef:
      key: {{ .Values.externalCert.certPrefix }}-crt
  - secretKey: tls.key
    remoteRef:
      key: {{ .Values.externalCert.certPrefix }}-key

