apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.cloud-service-account.clusterSecretName }}
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h             
  secretStoreRef:
    kind: SecretStore
    name: gcp-store 
  target:
    name: {{ .Values.cloud-service-account.clusterSecretName }}
    creationPolicy: Owner  
  data:
  - secretKey: private-key
    remoteRef:
      key: {{ .Values.cloud-service-account.googleSecretPrefix }}-private-key
  - secretKey: private-id
    remoteRef:
      key: {{ .Values.cloud-service-account.googleSecretPrefix }}-private-id