{{- if eq .Values.environment.sapigType "ob" }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.ig.ob.signingKey.clusterSecretName }}
spec:
  refreshInterval: 1h             
  secretStoreRef:
    kind: SecretStore
    name: gcp-store               
  target:
    name: {{ .Values.ig.ob.signingKey.clusterSecretName }}
    creationPolicy: Owner
  data:
  - secretKey: ig-core-signing-key.p12
    remoteRef:
      key: {{ .Values.ig.ob.signingKey.googleSecretName }}
{{ end }}