apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.ig.truststore.clusterSecretName }}
spec:
  refreshInterval: 1h             
  secretStoreRef:
    kind: SecretStore
    name: gcp-store               
  target:
    name: {{ .Values.ig.truststore.clusterSecretName }}
    creationPolicy: Owner
  data:
  - secretKey: ig-truststore.pem
    remoteRef:
      key: {{ .Values.ig.truststore.googleSecretName }}
