apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.ig.testTrustedDirectory.clusterSecretName }}
spec:
  refreshInterval: 1h             
  secretStoreRef:
    kind: SecretStore
    name: gcp-store               
  target:
    name: {{ .Values.ig.testTrustedDirectory.clusterSecretName }}
    creationPolicy: Owner
  data:
  - secretKey: test-trusted-dir-keystore.p12
    remoteRef:
      key: {{ .Values.ig.testTrustedDirectory.googleSecretName }}
