apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gcp-store
  annotations:
    "helm.sh/hook": pre-install
spec:
  provider:
    gcpsm:
      projectID: {{ .Values.externalCert.projectId }}
