{{- if eq .Values.environment.fr_platform.type "FIDC" }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.name }}
spec:
  secretStoreRef:
    kind: SecretStore
    name: gcp-store
  target:
    name: {{ .Values.name }}
    creationPolicy: Owner
  data:
    - secretKey: cdm-admin-password
      remoteRef:
        key: {{ .Values.version }}-cdm-admin-password
    - secretKey: cdm-admin-user
      remoteRef:
        key: {{ .Values.version }}-cdm-admin-user
{{ end }}