apiVersion: v1
kind: Service
metadata:
  name: ingress-mutator
spec:
  publishNotReadyAddresses: true
  type: ClusterIP
  ports:
    - port: 443
      targetPort: 8080
  selector:
    app: ingress-mutator